### ISSUE TITLE
Question/Clarification on Realtime Websocket Bytes Format 

### ISSUE THREAD

**Issue by jackspirou** [AssemblyAI/assemblyai-go-sdk#12]
Hello and thanks for the recent [release](https://github.com/AssemblyAI/assemblyai-go-sdk/releases/tag/v1.2.0), especially the features around `ForceEndUtterance` and `SetEndUtteranceSilenceThreshold`.  Will be using those updates in the future. 

I had a question about how the realtime portion of this SDK formats and sends audio.  I noticed on the [official API docs](https://www.assemblyai.com/docs/guides/real-time-streaming-transcription#sending-audio) it says:

> When sending audio over the WebSocket connection, you can use the websocket's binary mode to send raw audio data. This can be the raw data recorded directly from a microphone or read from an audio file.

and slightly lower down...

> HEADS UP
Sending audio_data via JSON is also supported but will be deprecated in the future. Use the binary mode instead.

If I look in the codebase I find the following: 
https://github.com/AssemblyAI/assemblyai-go-sdk/blob/8e723bf3efcfb49015108f7463f9ff5a79e80fa2/realtime.go#L310

Given that `&msg` here is using a [json.RawMessage](https://pkg.go.dev/encoding/json#RawMessage) type, it seems the realtime SDK is sending the bytes of a json message, but not the raw audio bytes themselves.  Is that coming in a future release? 

Its possible I am mistaken in how the SDK is working or I don't understand what the API docs are referring to when it comes to "raw audio bytes"?  I would assume it means PCM bytes.  Looking for clarification.

Thanks for the help!

**Comment by marcusolsson** [comment]
Hi @jackspirou 👋

As you've noticed, the SDK still sends the `audio_data` behind the scenes. This will be changed to send the data as binary data.

This is merely changing how the request is sent to the API and doesn't affect the audio format itself. Users of the Go SDK won't need to make any changes.

Let me know if you still have any questions!

**Comment by marcusolsson** [comment]
I've updated this upstreams. It'll be available in the next release. No action needed on your part.

**Comment by marcusolsson** [comment]
This has been fixed in [v1.3.0](https://github.com/AssemblyAI/assemblyai-go-sdk/releases/tag/v1.3.0).

**Comment by jackspirou** [comment]
Thank you @marcusolsson !
