### ISSUE TITLE
TemporaryTokens for realtime are defined but unused

### ISSUE THREAD

**Issue by qhenkart** [AssemblyAI/assemblyai-go-sdk#14]
Ideally I would be able to make a request to get the temporary token https://www.assemblyai.com/docs/guides/real-time-streaming-transcription#creating-temporary-authentication-tokens

The structs are there, but are not used anywhere. Either the package should be updated to include that function, or there should be a generic http function to make calls to unimplemented AssemblyAI endpoints without having to do all of the set up manually for one endpoint 
 
https://github.com/AssemblyAI/assemblyai-go-sdk/blob/main/types.go#L90
https://github.com/AssemblyAI/assemblyai-go-sdk/blob/main/types.go#L280

**Comment by marcusolsson** [comment]
Hey @qhenkart,

Temporary auth tokens are not yet supported in the Go SDK. The type is there because we generate them from our OpenAPI spec.

Temporary auth tokens are mainly used for client applications to avoid exposing your API key. Since Go applications typically run server-side, we decided to collect user feedback before adding it.

Would you mind sharing a bit about your use case? 🙏

**Comment by qhenkart** [comment]
@marcusolsson To avoid exposing the API key, the Temporary token needs to be generated on the server and supplied to the client. If the client is the one asking for a temporary token while supplying its API key to do so, then it defeats the purpose of avoiding exposure since the key will be clearly defined in the client side code

I would actually be curious what other usecase there _could_ be for a temporary token of this nature

Client clicks button to Transcribe
Request to server for temporary token
Server authorizes and validates the request, then returns a temporary token
Client uses that token to create a transcription websocket directly with Assembly

Am I misunderstanding the interaction?

**Comment by qhenkart** [comment]
also worth noting the official Python SDK supports this functionality
https://github.com/AssemblyAI/assemblyai-python-sdk/blob/master/assemblyai/transcriber.py#L1201

**Comment by marcusolsson** [comment]
Thank you for sharing! 🙏 I'll add support for temporary tokens in the coming days.

**Comment by marcusolsson** [comment]
v1.4.0 was just released with support for temporary tokens. You can find examples in the [release notes](https://github.com/AssemblyAI/assemblyai-go-sdk/releases/tag/v1.4.0). Let me know if you experience any issues 🙏
